CREATE TABLE IF NOT EXISTS orders (
    id              INT UNSIGNED NOT NULL AUTO_INCREMENT,
    order_number    VARCHAR(20) NOT NULL,
    user_id         INT UNSIGNED DEFAULT NULL,
    mobile          VARCHAR(15) NOT NULL,
    first_name      VARCHAR(80) NOT NULL,
    last_name       VARCHAR(80) NOT NULL,
    tool_id         INT UNSIGNED NOT NULL,
    plan_id         INT UNSIGNED NOT NULL,
    tool_name       VARCHAR(120) NOT NULL,
    plan_name       VARCHAR(120) NOT NULL,
    mode_type       ENUM('email_password','organization_id') NOT NULL,
    email           VARCHAR(190) DEFAULT NULL,
    password_enc    TEXT DEFAULT NULL,
    organization_id VARCHAR(190) DEFAULT NULL,
    price_usdt      DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    price_irt       BIGINT UNSIGNED NOT NULL DEFAULT 0,
    payment_method  ENUM('online','card_to_card') NOT NULL DEFAULT 'card_to_card',
    receipt_path    VARCHAR(255) DEFAULT NULL,
    status          ENUM('pending_payment','pending_review','approved','rejected','delivered') NOT NULL DEFAULT 'pending_payment',
    ip_address      VARCHAR(45) DEFAULT NULL,
    user_agent      VARCHAR(255) DEFAULT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_orders_number (order_number),
    KEY idx_orders_status (status),
    KEY idx_orders_mobile (mobile),
    KEY idx_orders_tool (tool_id),
    KEY idx_orders_plan (plan_id),
    KEY idx_orders_created (created_at),
    CONSTRAINT fk_orders_tool FOREIGN KEY (tool_id) REFERENCES tools (id) ON DELETE RESTRICT,
    CONSTRAINT fk_orders_plan FOREIGN KEY (plan_id) REFERENCES plans (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
